USE sge;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS academic_year;
DROP TABLE IF EXISTS school;
DROP TABLE IF EXISTS license;

SET FOREIGN_KEY_CHECKS = 1;

DROP DATABASE IF EXISTS sge;

CREATE DATABASE sge
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE sge;

COMMIT;